- name: Test playbook
  hosts: all
  vars:
    latest_release
  tasks:
    - debug: var=ansible_facts
    - name: Get latest release of a public repository Node-Red
      github_release:
        user: node-red
        repo: node-red
        action: latest_release
    - debug: var=latest_release
