- name: Hello World Sample
  hosts: all
  tasks:
    - name: Get latest release of a public repository
      github_release:
        user: node-red
        repo: node-red
        action: latest_release
