- name: Set version var manually
  hosts: all
  #gather_facts: yes
  vars:

  tasks:

   # - name: Display result preset
    #  debug:
     #   msg: "{{ ansible_facts['installed_release'] }}"

    - name: Set fact installed version ad hoc to 1.X.X
      set_fact:
        installed_release: "1.2.7"
        cacheable: yes

    - name: Display result
      debug:
        msg: "{{ ansible_facts['installed_release'] }}"

